name: "test-action"
author: "Tom van den Berg, Dylan van Gils"
description: "test description"
inputs:
  pathToProjectfile:
    description: "Path to the csproj file to run Stryker on."
    required: true

outputs:
  testOutput:
    description: "some output here"

volumes:
  - ${{GITHUB_WORKSPACE}}:/workspace

runs:
  using: 'docker'
  image: 'execute.dockerfile'
  args:
    - ${{ inputs.pathToProjectfile }}
