name: "Run-Stryker-DotNet"
author: "Tom van den Berg, Dylan van Gils"
description: "test description"
branding:
  icon: 'zap'
  color: 'green'
inputs:
  testProject:
    description: "The path to the test project directory (e.g. BusinessLogic.Test/)"
    required: true

runs:
  using: 'docker'
  image: 'dockerfile'
  args:
    - ${{ inputs.testProject }}
